version: "3.1"
services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dpt
      MYSQL_PASSWORD: dpt123
      MYSQL_DATABASE: db_board
    ports:
      - 3306:3306
    volumes:
      - mysql_data_container:/data/db

volumes:
  mysql_data_container:
