# Caminho para o changelog principal
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yml

# Configurações do banco de dados
url=jdbc:mysql://localhost:3306/db_board?useSSL=false&serverTimezone=UTC
username=dpt
password=dpt123
driver=com.mysql.cj.jdbc.Driver

# Caminho onde está o driver JDBC
classpath=lib
